name: Dart Analyzer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        id: dart_analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Scores
        env:
          TOTAL: ${{ steps.dart_analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.dart_analysis.outputs.total_max }}
        run: |
          SCORES=$(( $TOTAL + 10 / $TOTAL_MAX + 10 ))
          if (( $SCORES < 0.8 ))
          then
            echo Score too low!
            exit 1
          fi